app/controllers/GirlsController.php
<?php

namespace app\controllers;

use app\models\GuestbookForm;
use yii\easyii\modules\carousel\api\Carousel;
use yii\easyii\modules\catalog\api\Catalog;
use yii\easyii\modules\entity\api\Entity;
use yii\easyii\modules\gallery\api\Gallery;
use yii\easyii\modules\guestbook\api\Guestbook;
use yii\easyii\modules\page\api\Page;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Yii;
use app\models\Feedback as FeedbackModel;

class GirlsController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Список девушек
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'page'=>$this->loadPage('girls'),
            'girls'=>Catalog::cat('devuski')->getItems(),
            'salony'=>Entity::cat('salony')->getItems(),
            'guestbook' => Guestbook::items([
                'pagination' => [
                    'pageSize' => 5,
                ],
            ]),
        ]);
    }

    /**
     * Профайл девушки
     * @param string $slug
     * @return string
     */
    public function actionView($slug)
    {
        return $this->render('view', [
            'page'=>$this->loadPage('girls'),
            'girl'=>Catalog::get($slug),
            'girls'=>Catalog::cat('devuski')->getItems(),
            'salony'=>Entity::cat('salony')->getItems(),
            'guestbook' => Guestbook::items([
                'pagination' => [
                    'pageSize' => 5,
                ],
            ]),
        ]);
    }

    /**
     * @param string $slug
     * @return string
     * @throws NotFoundHttpException
     */
    protected function loadPage($slug){
        $page = Page::get($slug);
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $page;
    }
}

app/views/girls/_item.php
<?php
/**
 * User: Alexander Popov <b059ae@gmail.com>
 * Date: 22.08.17
 * Time: 18:01
 */
/** @var $girl \yii\easyii\modules\catalog\api\ItemObject  */
?>
<div class="col-sm-6 col-md-3 girl">
    <a href="<?= \yii\helpers\Url::to(['/girls/view', 'slug' => $girl->slug]) ?>">
        <div class="girl-wrapper"
             style="background-image: url('<?= $girl->thumb(267, 400) ?>')">
            <!--<a href="#" class="girl_link">-->
            <div class="info">
                <h4 class="name"><?= $girl->title ?></h4>
            </div>
        </div>
    </a>
</div>

app/views/girls/_view.php
<?php
/**
 * User: Alexander Popov <b059ae@gmail.com>
 * Date: 22.08.17
 * Time: 18:14
 */

use yii\easyii\modules\catalog\api\PhotoObject;
use yii\helpers\Html;

/** @var $girl \yii\easyii\modules\catalog\api\ItemObject */
\yii\easyii\widgets\Fancybox::widget([
    'selector' => '.fancybox',
]);
?>
<div id="girl" class="black text-center">
    <h2><?= $girl->title ?></h2>
    <div class="map-fill">
        <div class="container">
            <div class="row single_girl">
                <div class="col-md-5">
                    <!-- Основная картинка -->
                    <?= Html::img($girl->thumb(740)); ?>
                    <!-- /Основная картинка -->
                </div>
                <div class="col-md-7">
                    <!-- Форма для записи -->
                    <h4 class="name">Записаться на прием</h4>
                    <div id="appointment-form">
                        <?= \app\widgets\GalleryForm::widget([
                            'id' => 'form-gallery',
                        ]) ?>
                    </div>
                    <p>Перезвоним за 27 секунд</p>
                    <p>Ваши контактные данные не будут
                        передаваться третьим лицам</p>
                    <!-- /Форма для записи -->
                    <div class="row images">
                        <!-- Дополнительные картинки -->
                        <div class="image col-md-3 col-xs-6">
                            <a href="<?= $girl->getImage() ?>" class="fancybox">
                                <?= Html::img($girl->thumb(120, 160)); ?>
                            </a>
                        </div>
                        <?php
                        /** @var PhotoObject $photo */
                        foreach (array_slice($girl->getPhotos(), 0, 3) as $photo) : ?>
                            <div class="image col-md-3 col-xs-6">
                                <a href="<?= $photo->getImage() ?>" class="fancybox">
                                    <?= Html::img($photo->thumb(120, 160)); ?>
                                </a>
                            </div>
                        <?php endforeach; ?>
                        <!-- /Дополнительные картинки -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- end #map -->

app/views/girls/index.php
<?php
/**
 * @var $page \yii\easyii\modules\page\api\PageObject
 * @var $girls \yii\easyii\modules\catalog\api\ItemObject[]
 * @var $salony yii\easyii\modules\entity\api\ItemObject[]
 * @var $guestbook \yii\easyii\modules\guestbook\api\PostObject[]
 */
$asset = \app\assets\AppAsset::register($this);

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title');

?>
<?= $this->render('//site/slides/girls', ['asset' => $asset, 'girls' => $girls, 'title' => 'Мастера массажа']); ?>
<?= $this->render('//site/slides/guestbook', ['asset' => $asset, 'guestbook' => $guestbook]); ?>
<?= $this->render('//site/slides/map', ['asset' => $asset, 'salony' => $salony]); ?>

app/views/girls/view.php
<?php
/**
 * @var $page \yii\easyii\modules\page\api\PageObject
 * @var $girl \yii\easyii\modules\catalog\api\ItemObject
 * @var $girls \yii\easyii\modules\catalog\api\ItemObject[]
 * @var $salony yii\easyii\modules\entity\api\ItemObject[]
 * @var $guestbook \yii\easyii\modules\guestbook\api\PostObject[]
 */
$asset = \app\assets\AppAsset::register($this);

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title') . ' - ' . $girl->getTitle();
?>
<!-- Профайл -->
<?= $this->render('_view', ['girl' => $girl]); ?>
<!-- /Профайл -->
<?= $this->render('//site/slides/girls', ['asset' => $asset, 'girls' => $girls, 'title' => 'Другие мастера']); ?>
<?= $this->render('//site/slides/guestbook', ['asset' => $asset, 'guestbook' => $guestbook]); ?>
<?= $this->render('//site/slides/map', ['asset' => $asset, 'salony' => $salony]); ?>